// Rebuild after editing the homepage scripts, styles, or English catalog.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
const root = new URL('../', import.meta.url);
const read = name => readFileSync(new URL(name, root), 'utf8');
const banner = '/* Generated by scripts/build-site.mjs. Edit source files, then rebuild. */\n';
writeFileSync(new URL('site.css', root), banner + ['style.css','home.css','i18n.css'].map(read).join('\n'));
writeFileSync(new URL('site.js', root), banner + `window.FRUIT_ENGLISH=${JSON.stringify(JSON.parse(read('locales/en.json')))};\n` + ['content.js','home.js','i18n.js'].map(read).join('\n;\n'));
console.log('Built site.css and site.js');
